// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToMemo(arg1, arg2) {
  return window['go']['main']['App']['AddTagToMemo'](arg1, arg2);
}

export function CheckClaudeInstalled() {
  return window['go']['main']['App']['CheckClaudeInstalled']();
}

export function CreateMemo(arg1) {
  return window['go']['main']['App']['CreateMemo'](arg1);
}

export function DeleteBlogDraft(arg1) {
  return window['go']['main']['App']['DeleteBlogDraft'](arg1);
}

export function DeleteMemo(arg1) {
  return window['go']['main']['App']['DeleteMemo'](arg1);
}

export function GenerateBlogDraft(arg1, arg2) {
  return window['go']['main']['App']['GenerateBlogDraft'](arg1, arg2);
}

export function GetBacklinks(arg1) {
  return window['go']['main']['App']['GetBacklinks'](arg1);
}

export function GetBlogDraft(arg1) {
  return window['go']['main']['App']['GetBlogDraft'](arg1);
}

export function GetMemo(arg1) {
  return window['go']['main']['App']['GetMemo'](arg1);
}

export function GetMemoTags(arg1) {
  return window['go']['main']['App']['GetMemoTags'](arg1);
}

export function GetMemosByTag(arg1) {
  return window['go']['main']['App']['GetMemosByTag'](arg1);
}

export function ListBlogDrafts() {
  return window['go']['main']['App']['ListBlogDrafts']();
}

export function ListMemos(arg1, arg2) {
  return window['go']['main']['App']['ListMemos'](arg1, arg2);
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function RemoveTagFromMemo(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromMemo'](arg1, arg2);
}

export function ResolveWikiLinks(arg1) {
  return window['go']['main']['App']['ResolveWikiLinks'](arg1);
}

export function SearchMemos(arg1) {
  return window['go']['main']['App']['SearchMemos'](arg1);
}

export function SearchTags(arg1) {
  return window['go']['main']['App']['SearchTags'](arg1);
}

export function SuggestTags(arg1) {
  return window['go']['main']['App']['SuggestTags'](arg1);
}

export function UpdateBlogDraft(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateBlogDraft'](arg1, arg2, arg3);
}

export function UpdateMemo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMemo'](arg1, arg2, arg3);
}

export function GetWeeklyReport() {
  return window['go']['main']['App']['GetWeeklyReport']();
}

export function GetTopicSuggestions() {
  return window['go']['main']['App']['GetTopicSuggestions']();
}

export function CheckNudge() {
  return window['go']['main']['App']['CheckNudge']();
}

export function DismissCoachLog(arg1) {
  return window['go']['main']['App']['DismissCoachLog'](arg1);
}

export function GetCoachLogs(arg1, arg2) {
  return window['go']['main']['App']['GetCoachLogs'](arg1, arg2);
}
