// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memo} from '../models';
import {ai} from '../models';

export function CheckClaudeInstalled():Promise<boolean>;

export function CreateMemo(arg1:string):Promise<memo.Memo>;

export function DeleteBlogDraft(arg1:string):Promise<void>;

export function DeleteMemo(arg1:string):Promise<void>;

export function GenerateBlogDraft(arg1:Array<string>,arg2:string):Promise<ai.BlogDraft>;

export function GetBlogDraft(arg1:string):Promise<ai.BlogDraft>;

export function GetMemo(arg1:string):Promise<memo.Memo>;

export function ListBlogDrafts():Promise<Array<ai.BlogDraftSummary>>;

export function ListMemos(arg1:number,arg2:number):Promise<Array<memo.MemoSummary>>;

export function SearchMemos(arg1:string):Promise<Array<memo.MemoSummary>>;

export function UpdateBlogDraft(arg1:string,arg2:any,arg3:any):Promise<ai.BlogDraft>;

export function UpdateMemo(arg1:string,arg2:any,arg3:any):Promise<memo.Memo>;
