// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMemo(arg1) {
  return window['go']['main']['App']['CreateMemo'](arg1);
}

export function DeleteMemo(arg1) {
  return window['go']['main']['App']['DeleteMemo'](arg1);
}

export function GetMemo(arg1) {
  return window['go']['main']['App']['GetMemo'](arg1);
}

export function ListMemos(arg1, arg2) {
  return window['go']['main']['App']['ListMemos'](arg1, arg2);
}

export function SearchMemos(arg1) {
  return window['go']['main']['App']['SearchMemos'](arg1);
}

export function UpdateMemo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMemo'](arg1, arg2, arg3);
}
