// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tag} from '../models';
import {ai} from '../models';
import {memo} from '../models';
import {wiki} from '../models';

export function AddTagToMemo(arg1:string,arg2:string):Promise<tag.Tag>;

export function CheckClaudeInstalled():Promise<boolean>;

export function CheckNudge():Promise<ai.NudgeMessage>;

export function CreateMemo(arg1:string):Promise<memo.Memo>;

export function DeleteBlogDraft(arg1:string):Promise<void>;

export function DeleteMemo(arg1:string):Promise<void>;

export function DismissCoachLog(arg1:string):Promise<void>;

export function GenerateBlogDraft(arg1:Array<string>,arg2:string):Promise<ai.BlogDraft>;

export function GetBacklinks(arg1:string):Promise<Array<wiki.BacklinkInfo>>;

export function GetBlogDraft(arg1:string):Promise<ai.BlogDraft>;

export function GetCoachLogs(arg1:string,arg2:number):Promise<Array<ai.CoachLog>>;

export function GetLastSynced():Promise<string>;

export function GetMemo(arg1:string):Promise<memo.Memo>;

export function GetMemoTags(arg1:string):Promise<Array<tag.Tag>>;

export function GetMemosByTag(arg1:string):Promise<Array<string>>;

export function GetSyncStatus():Promise<string>;

export function GetTopicSuggestions():Promise<Array<ai.TopicSuggestion>>;

export function GetWeeklyReport():Promise<ai.WeeklyReport>;

export function ListBlogDrafts():Promise<Array<ai.BlogDraftSummary>>;

export function ListMemos(arg1:number,arg2:number):Promise<Array<memo.MemoSummary>>;

export function ListTags():Promise<Array<tag.TagWithCount>>;

export function RemoveTagFromMemo(arg1:string,arg2:string):Promise<void>;

export function ResolveWikiLinks(arg1:Array<string>):Promise<Array<wiki.ResolvedLink>>;

export function SearchMemos(arg1:string):Promise<Array<memo.MemoSummary>>;

export function SearchTags(arg1:string):Promise<Array<tag.Tag>>;

export function SuggestTags(arg1:string):Promise<Array<string>>;

export function SyncNow():Promise<void>;

export function UpdateBlogDraft(arg1:string,arg2:any,arg3:any):Promise<ai.BlogDraft>;

export function UpdateMemo(arg1:string,arg2:any,arg3:any):Promise<memo.Memo>;
